model:
    model_arch: 'deit_tiny_patch16_224'
    epochs: 200
    batch_size: 8
    learning_rate: 5e-4
    weight_decay: 1e-3
    embed_dim: 192
    alpha: 0.5
    input_size: 224

dataset:
    dataset_name: 'flowers'
    dataset_root_path: '/home/phemiloye/Desktop/Research/code-base/data/flowers-102'
    df_train: 'train.csv'
    df_trainval: train_val.csv
    df_val: 'val.csv'
    df_test: 'test.csv'
    folder_train: 'jpg'
    folder_val: 'jpg'
    folder_test: 'jpg'
    df_classid_classname: 'classid_classname.csv'

project_name: 'parametric-instance-discrimination-reproduction'
ckpt_path: 'checkpoints/224_finetune/flowers/deit_tiny_patch16_224_lr_0.0005_wd_0.001_bs_8_epochs_200_dim_192_cutmix_0.5_path_flowerspretrained_deit_tiny/checkpoint_0000.pth.tar'