model:
    model_arch: 'resnet18_224'
    epochs: 200
    batch_size: 4
    learning_rate: 5e-4
    weight_decay: 0.001
    embed_dim: 192
    alpha: 0.5
    input_size: 224

dataset:
    dataset_name: 'flowers'
    dataset_root_path: '/home/phemiloye/Desktop/Research/code-base/data/flowers-102'
    df_train: 'train.csv'
    df_trainval: train_val.csv
    df_val: 'val.csv'
    df_test: 'test.csv'
    folder_train: 'jpg'
    folder_val: 'jpg'
    folder_test: 'jpg'
    df_classid_classname: 'classid_classname.csv'

project_name: 'IDMM-reproduction'
ckpt_path: 'checkpoints/instance_discrimination/flowers/resnet18_224_lr_0.0005_wd_0.001_bs_4_epochs_200_path_flowerscutmix_0.5crops_112_2_112_4/checkpoint_0000.pth.tar'